#ifndef QR_PAYMENT_H
#define QR_PAYMENT_H

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

typedef struct {
    char payment_id[30];
    char upi_id[100];
    int amount;
    char date[50];
    char status[20];  // pending, completed, failed
} PaymentRecord;

// Function to create advanced QR code with additional features
void generate_advanced_qr_code(int amount, char payment_id[50], char upi_id[100], char merchant_name[100]) {
    FILE *html_file = fopen("qr_payment.html", "w");
    if (html_file == NULL) {
        printf("Error creating payment page!\n");
        return;
    }

    fprintf(html_file, "<!DOCTYPE html>\n");
    fprintf(html_file, "<html lang='en'>\n");
    fprintf(html_file, "<head>\n");
    fprintf(html_file, "    <meta charset='UTF-8'>\n");
    fprintf(html_file, "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n");
    fprintf(html_file, "    <title>Hotel Payment - Advanced QR Code</title>\n");
    fprintf(html_file, "    <script src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js'></script>\n");
    fprintf(html_file, "    <style>\n");
    fprintf(html_file, "        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
    fprintf(html_file, "        body { \n");
    fprintf(html_file, "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
    fprintf(html_file, "            background: linear-gradient(135deg, #667eea 0%%, #764ba2 100%%);\n");
    fprintf(html_file, "            min-height: 100vh;\n");
    fprintf(html_file, "            display: flex;\n");
    fprintf(html_file, "            justify-content: center;\n");
    fprintf(html_file, "            align-items: center;\n");
    fprintf(html_file, "            padding: 20px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .main-container {\n");
    fprintf(html_file, "            background: white;\n");
    fprintf(html_file, "            border-radius: 20px;\n");
    fprintf(html_file, "            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n");
    fprintf(html_file, "            padding: 40px;\n");
    fprintf(html_file, "            max-width: 600px;\n");
    fprintf(html_file, "            width: 100%%;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .header {\n");
    fprintf(html_file, "            text-align: center;\n");
    fprintf(html_file, "            margin-bottom: 35px;\n");
    fprintf(html_file, "            border-bottom: 3px solid #667eea;\n");
    fprintf(html_file, "            padding-bottom: 20px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .hotel-logo {\n");
    fprintf(html_file, "            width: 60px;\n");
    fprintf(html_file, "            height: 60px;\n");
    fprintf(html_file, "            background: linear-gradient(135deg, #667eea, #764ba2);\n");
    fprintf(html_file, "            border-radius: 50%%;\n");
    fprintf(html_file, "            display: inline-flex;\n");
    fprintf(html_file, "            align-items: center;\n");
    fprintf(html_file, "            justify-content: center;\n");
    fprintf(html_file, "            color: white;\n");
    fprintf(html_file, "            font-size: 30px;\n");
    fprintf(html_file, "            margin-bottom: 15px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .header h1 { color: #333; font-size: 28px; margin-bottom: 5px; }\n");
    fprintf(html_file, "        .hotel-name { color: #667eea; font-size: 14px; font-weight: bold; }\n");
    fprintf(html_file, "        .payment-card {\n");
    fprintf(html_file, "            background: linear-gradient(135deg, #667eea 0%%, #764ba2 100%%);\n");
    fprintf(html_file, "            color: white;\n");
    fprintf(html_file, "            padding: 30px;\n");
    fprintf(html_file, "            border-radius: 15px;\n");
    fprintf(html_file, "            margin-bottom: 25px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .card-row {\n");
    fprintf(html_file, "            display: flex;\n");
    fprintf(html_file, "            justify-content: space-between;\n");
    fprintf(html_file, "            margin-bottom: 15px;\n");
    fprintf(html_file, "            font-size: 14px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .card-label { opacity: 0.8; }\n");
    fprintf(html_file, "        .card-value { font-weight: bold; }\n");
    fprintf(html_file, "        .amount-section {\n");
    fprintf(html_file, "            background: rgba(255,255,255,0.2);\n");
    fprintf(html_file, "            padding: 15px;\n");
    fprintf(html_file, "            border-radius: 10px;\n");
    fprintf(html_file, "            text-align: center;\n");
    fprintf(html_file, "            margin-top: 15px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .amount { font-size: 32px; font-weight: bold; }\n");
    fprintf(html_file, "        .qr-container {\n");
    fprintf(html_file, "            background: #f8f9fa;\n");
    fprintf(html_file, "            padding: 30px;\n");
    fprintf(html_file, "            border-radius: 15px;\n");
    fprintf(html_file, "            text-align: center;\n");
    fprintf(html_file, "            margin: 25px 0;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .qr-title {\n");
    fprintf(html_file, "            color: #333;\n");
    fprintf(html_file, "            font-size: 16px;\n");
    fprintf(html_file, "            font-weight: bold;\n");
    fprintf(html_file, "            margin-bottom: 20px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        #qrcode {\n");
    fprintf(html_file, "            display: inline-block;\n");
    fprintf(html_file, "            padding: 15px;\n");
    fprintf(html_file, "            background: white;\n");
    fprintf(html_file, "            border: 2px solid #667eea;\n");
    fprintf(html_file, "            border-radius: 10px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .info-box {\n");
    fprintf(html_file, "            background: #e3f2fd;\n");
    fprintf(html_file, "            border-left: 4px solid #2196f3;\n");
    fprintf(html_file, "            padding: 15px;\n");
    fprintf(html_file, "            border-radius: 5px;\n");
    fprintf(html_file, "            margin-bottom: 15px;\n");
    fprintf(html_file, "            color: #1565c0;\n");
    fprintf(html_file, "            font-size: 13px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .instructions {\n");
    fprintf(html_file, "            background: #fff3cd;\n");
    fprintf(html_file, "            border-left: 4px solid #ffc107;\n");
    fprintf(html_file, "            padding: 20px;\n");
    fprintf(html_file, "            border-radius: 5px;\n");
    fprintf(html_file, "            margin: 20px 0;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .instructions h4 {\n");
    fprintf(html_file, "            color: #856404;\n");
    fprintf(html_file, "            margin-bottom: 12px;\n");
    fprintf(html_file, "            font-size: 14px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .instructions ol {\n");
    fprintf(html_file, "            margin-left: 20px;\n");
    fprintf(html_file, "            color: #856404;\n");
    fprintf(html_file, "            font-size: 13px;\n");
    fprintf(html_file, "            line-height: 1.8;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .supported-apps {\n");
    fprintf(html_file, "            display: grid;\n");
    fprintf(html_file, "            grid-template-columns: 1fr 1fr 1fr;\n");
    fprintf(html_file, "            gap: 10px;\n");
    fprintf(html_file, "            margin-top: 15px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .app-badge {\n");
    fprintf(html_file, "            background: #f0f0f0;\n");
    fprintf(html_file, "            padding: 8px;\n");
    fprintf(html_file, "            border-radius: 5px;\n");
    fprintf(html_file, "            font-size: 12px;\n");
    fprintf(html_file, "            text-align: center;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .status-bar {\n");
    fprintf(html_file, "            margin-top: 25px;\n");
    fprintf(html_file, "            padding: 15px;\n");
    fprintf(html_file, "            border-radius: 10px;\n");
    fprintf(html_file, "            text-align: center;\n");
    fprintf(html_file, "            font-weight: bold;\n");
    fprintf(html_file, "            font-size: 14px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .status-bar.pending {\n");
    fprintf(html_file, "            background: #fffde7;\n");
    fprintf(html_file, "            color: #f57f17;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .status-bar.success {\n");
    fprintf(html_file, "            background: #c8e6c9;\n");
    fprintf(html_file, "            color: #2e7d32;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .timer {\n");
    fprintf(html_file, "            color: #d32f2f;\n");
    fprintf(html_file, "            font-weight: bold;\n");
    fprintf(html_file, "            margin-top: 10px;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        .footer {\n");
    fprintf(html_file, "            text-align: center;\n");
    fprintf(html_file, "            margin-top: 30px;\n");
    fprintf(html_file, "            padding-top: 20px;\n");
    fprintf(html_file, "            border-top: 1px solid #ddd;\n");
    fprintf(html_file, "            color: #666;\n");
    fprintf(html_file, "            font-size: 12px;\n");
    fprintf(html_file, "            line-height: 1.6;\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        @media (max-width: 600px) {\n");
    fprintf(html_file, "            .main-container { padding: 20px; }\n");
    fprintf(html_file, "            .payment-card { padding: 20px; }\n");
    fprintf(html_file, "            .amount { font-size: 24px; }\n");
    fprintf(html_file, "            .supported-apps { grid-template-columns: 1fr 1fr; }\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "    </style>\n");
    fprintf(html_file, "</head>\n");
    fprintf(html_file, "<body>\n");
    fprintf(html_file, "    <div class='main-container'>\n");
    fprintf(html_file, "        <div class='header'>\n");
    fprintf(html_file, "            <div class='hotel-logo'>🏨</div>\n");
    fprintf(html_file, "            <h1>Secure Payment</h1>\n");
    fprintf(html_file, "            <div class='hotel-name'>%s</div>\n", merchant_name);
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='payment-card'>\n");
    fprintf(html_file, "            <div class='card-row'>\n");
    fprintf(html_file, "                <span class='card-label'>Transaction ID:</span>\n");
    fprintf(html_file, "                <span class='card-value'>%s</span>\n", payment_id);
    fprintf(html_file, "            </div>\n");
    fprintf(html_file, "            <div class='card-row'>\n");
    fprintf(html_file, "                <span class='card-label'>Merchant:</span>\n");
    fprintf(html_file, "                <span class='card-value'>%s</span>\n", merchant_name);
    fprintf(html_file, "            </div>\n");
    fprintf(html_file, "            <div class='card-row'>\n");
    fprintf(html_file, "                <span class='card-label'>Time:</span>\n");
    fprintf(html_file, "                <span class='card-value' id='time'></span>\n");
    fprintf(html_file, "            </div>\n");
    fprintf(html_file, "            <div class='amount-section'>\n");
    fprintf(html_file, "                <p style='opacity: 0.8; margin-bottom: 5px;'>Amount to Pay</p>\n");
    fprintf(html_file, "                <div class='amount'>₹%d</div>\n", amount);
    fprintf(html_file, "            </div>\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='info-box'>\n");
    fprintf(html_file, "            ℹ️ This payment is valid for 15 minutes. Your room booking will be confirmed immediately after payment.\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='qr-container'>\n");
    fprintf(html_file, "            <div class='qr-title'>📱 Scan with your UPI App</div>\n");
    fprintf(html_file, "            <div id='qrcode'></div>\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='instructions'>\n");
    fprintf(html_file, "            <h4>✅ Quick Payment Steps:</h4>\n");
    fprintf(html_file, "            <ol>\n");
    fprintf(html_file, "                <li>Open any UPI app from the list below</li>\n");
    fprintf(html_file, "                <li>Tap on 'Send Money' or 'Scan QR Code'</li>\n");
    fprintf(html_file, "                <li>Hold your phone over the QR code above</li>\n");
    fprintf(html_file, "                <li>Verify the amount and details</li>\n");
    fprintf(html_file, "                <li>Enter your UPI PIN</li>\n");
    fprintf(html_file, "                <li>Payment complete! ✓</li>\n");
    fprintf(html_file, "            </ol>\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='instructions' style='background: #f3e5f5; border-left-color: #9c27b0; color: #6a1b9a;'>\n");
    fprintf(html_file, "            <h4>🏦 Supported Payment Apps:</h4>\n");
    fprintf(html_file, "            <div class='supported-apps'>\n");
    fprintf(html_file, "                <div class='app-badge'>Google Pay</div>\n");
    fprintf(html_file, "                <div class='app-badge'>PhonePe</div>\n");
    fprintf(html_file, "                <div class='app-badge'>Paytm</div>\n");
    fprintf(html_file, "                <div class='app-badge'>BHIM</div>\n");
    fprintf(html_file, "                <div class='app-badge'>WhatsApp Pay</div>\n");
    fprintf(html_file, "                <div class='app-badge'>Amazon Pay</div>\n");
    fprintf(html_file, "            </div>\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='status-bar pending' id='status'>\n");
    fprintf(html_file, "            ⏳ Awaiting Payment\n");
    fprintf(html_file, "            <div class='timer' id='timer'>Payment expires in: <span id='countdown'>15:00</span></div>\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        <div class='footer'>\n");
    fprintf(html_file, "            <p><strong>Security Notice:</strong> Your payment is encrypted and secure. Your payment details will not be stored.</p>\n");
    fprintf(html_file, "            <p>For support: support@luxuryhotel.com | Phone: +1-800-HOTEL</p>\n");
    fprintf(html_file, "            <p>© 2026 Luxury Hotel Management. All rights reserved.</p>\n");
    fprintf(html_file, "        </div>\n");
    fprintf(html_file, "    </div>\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "    <script>\n");
    fprintf(html_file, "        // Generate QR Code with UPI standard format\n");
    fprintf(html_file, "        const upiString = 'upi://pay?pa=%s&pn=LuxuryHotel&am=%d&tr=%s&tn=Hotel%%20Booking';\n", upi_id, amount, payment_id);
    fprintf(html_file, "        \n");
    fprintf(html_file, "        new QRCode(document.getElementById('qrcode'), {\n");
    fprintf(html_file, "            text: upiString,\n");
    fprintf(html_file, "            width: 280,\n");
    fprintf(html_file, "            height: 280,\n");
    fprintf(html_file, "            colorDark: '#667eea',\n");
    fprintf(html_file, "            colorLight: '#ffffff',\n");
    fprintf(html_file, "            correctLevel: QRCode.CorrectLevel.H\n");
    fprintf(html_file, "        });\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        // Display current time\n");
    fprintf(html_file, "        function updateTime() {\n");
    fprintf(html_file, "            const now = new Date();\n");
    fprintf(html_file, "            const options = { hour: '2-digit', minute: '2-digit', second: '2-digit' };\n");
    fprintf(html_file, "            document.getElementById('time').textContent = now.toLocaleTimeString('en-US', options);\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        updateTime();\n");
    fprintf(html_file, "        setInterval(updateTime, 1000);\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        // Countdown timer (15 minutes)\n");
    fprintf(html_file, "        let timeLeft = 15 * 60; // 15 minutes in seconds\n");
    fprintf(html_file, "        function updateCountdown() {\n");
    fprintf(html_file, "            const minutes = Math.floor(timeLeft / 60);\n");
    fprintf(html_file, "            const seconds = timeLeft %% 60;\n");
    fprintf(html_file, "            document.getElementById('countdown').textContent = \n");
    fprintf(html_file, "                String(minutes).padStart(2, '0') + ':' + String(seconds).padStart(2, '0');\n");
    fprintf(html_file, "            \n");
    fprintf(html_file, "            if (timeLeft <= 0) {\n");
    fprintf(html_file, "                const status = document.getElementById('status');\n");
    fprintf(html_file, "                status.style.background = '#ffcdd2';\n");
    fprintf(html_file, "                status.style.color = '#c62828';\n");
    fprintf(html_file, "                status.textContent = '❌ Payment Expired! Please initiate a new transaction.';\n");
    fprintf(html_file, "            } else {\n");
    fprintf(html_file, "                timeLeft--;\n");
    fprintf(html_file, "            }\n");
    fprintf(html_file, "        }\n");
    fprintf(html_file, "        setInterval(updateCountdown, 1000);\n");
    fprintf(html_file, "\n");
    fprintf(html_file, "        // Simulate payment confirmation (for demo purposes)\n");
    fprintf(html_file, "        setTimeout(() => {\n");
    fprintf(html_file, "            const status = document.getElementById('status');\n");
    fprintf(html_file, "            status.className = 'status-bar success';\n");
    fprintf(html_file, "            status.innerHTML = '✅ Payment Successful!<br>Your room booking is confirmed. Confirmation email sent.';\n");
    fprintf(html_file, "        }, 25000); // Show success after 25 seconds\n");
    fprintf(html_file, "    </script>\n");
    fprintf(html_file, "</body>\n");
    fprintf(html_file, "</html>\n");

    fclose(html_file);
}

// Function to save payment record
void save_payment_record(PaymentRecord payment) {
    FILE *fp = fopen("payment_records.txt", "a");
    if (fp == NULL) {
        printf("Cannot save payment record!\n");
        return;
    }
    
    fprintf(fp, "Payment ID: %s\n", payment.payment_id);
    fprintf(fp, "UPI ID: %s\n", payment.upi_id);
    fprintf(fp, "Amount: %d\n", payment.amount);
    fprintf(fp, "Date: %s\n", payment.date);
    fprintf(fp, "Status: %s\n", payment.status);
    fprintf(fp, "-----------------------------------\n");
    
    fclose(fp);
}

#endif
